### ISSUE TITLE
Malformed code

### ISSUE THREAD

**Issue by V01D-NULL** [mentos-team/MentOS#15]
What's up with [all this?](https://github.com/mentos-team/MentOS/blob/master/mentos/src/mem/buddysystem.c#L148)

**Comment by Galfurian** [comment]
MentOs code is meant to be part of a University-level O.S. course. The following files:

- https://github.com/mentos-team/MentOS/blob/master/mentos/src/mem/buddysystem.c
- https://github.com/mentos-team/MentOS/blob/master/mentos/src/process/scheduler_algorithm.c

are meant to be modified after reading the two lessons (available at https://mentos-team.github.io):

- https://mentos-team.github.io/doc/mentos_2_process_management.pdf
- https://mentos-team.github.io/doc/mentos_4_memory_management.pdf

Whenever you see those comments, i.e. `/*...*/`, you should replace those comments with a line of code inspired by the lecture slides.

**Comment by V01D-NULL** [comment]
I see.
