### ISSUE TITLE
`O_TRUNC` has no effect

### ISSUE THREAD

**Issue by fischerling** [mentos-team/MentOS#33]
The `open(2)` flag `O_TRUNC` is currently not implemented.

An existing file is not truncated and the blocks used by the file are not freed.

This results in files containing old content, if it is longer than the newly written content, after using `O_TRUNC`.

```C

int fd = creat("foo", 660);
write(fd, "foobar", 6);
close(fd);

fd = open("foo", O_RDWR | O_TRUNC, 0); // File length should be set to 0.
write(fd, "baz", 3); // File should only contain "foo".
char buf[7] = {0};
read(fd, buf, 6); // This will read the six bytes "bazbar"
```

**Comment by Galfurian** [comment]
Yep, it does not reset the write and read location. I've extended the `t_write_read.c` test you've created to test the truncate behavior too.

In the meantime, I've found and solved a little bug in the `sys_write` function thanks to this issue.

That said, I'll solve the problem with the `O_TRUNC`.

**Comment by Galfurian** [comment]
Ok, I've fixed (actually, implemented LoL) the `O_TRUNC` in `ext2`.
