### ISSUE TITLE
List of issues found in Develop

### ISSUE THREAD

**Issue by The-Shapeshifter** [mentos-team/MentOS#7]
- when accessing as root you get a kernel panic as it tries to open the root dir
- ipcs and cpuid doesn't show any output
- when using cgdb, a warni appears for a file to be added (add-auto-load-safe-path /home/user/MentOS/build/.gdbinit string in /home/user/.config/gdb/gdbinit)
- modify and extend the documentation for the new update

**Comment by Galfurian** [comment]
All the things I've done are currently on the `develop` branch:
- [x] when accessing as root you get a kernel panic as it tries to open the root dir
 - The directory was missing, I've solved it by adding the `/root` directory, with a `.bashrc` inside.
- [ ] `ipcs` and `cpuid` doesn't show any output
 - It's meant to be like that, for now.
- [x] when using cgdb, a warni appears for a file to be added (add-auto-load-safe-path /home/user/MentOS/build/.gdbinit string in /home/user/.config/gdb/gdbinit)
 - I've completely updated/renewed the guidelines for debugging;
 - Now it should be easier to understand how it works;
 - There is no need for modifying user-related files, it's all done by the `Makefile' on the command line;
 - There is no need for `xterm`, you just need to open two bash instances;
 - Please, give it a try and let me know if it' better now the whole procedure.
- [x] modify and extend the documentation for the new update
 - I've extended the `README.md` file, and removed old stuff;

Thanks for your feedback!
