### ISSUE TITLE
Directory entries are dropped when new ones are created

### ISSUE THREAD

**Issue by fischerling** [mentos-team/MentOS#87]
Directories are still buggy.

I introduced two seperate user `alice` and `bob` in commit [225bcda](https://github.com/fischerling/MentOS/commit/225bcda842de281fdec47da8cc00a1111a93d1ad).
This is the first commit where I can reproduce the buggy behavior.
This behavior is independent of #82, because I could reproduce it after merging my modifications into the current master 4bc52fb08dff6be04c704d2c0a7e238b0e89c793.

## What happens?
When I create a new file in alice' home directory using `touch foo` all other directory entries are lost.

However, if I delete the `secrets.txt` file from alice' home before creating a new file all expected entries are found.
But creating a second file results in the same behavior, of loosing all entries except the newly created one.

fsck.ext2 reports unatteched inodes after creating a file `foo` as described above.

```
$ fsck.ext2 -fn rootfs.img

e2fsck 1.47.1 (20-May-2024)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Unattached inode 105
Connect to /lost+found? no

Unattached inode 106
Connect to /lost+found? no

Unattached inode 107
Connect to /lost+found? no

Pass 5: Checking group summary information

rootfs: ********** WARNING: Filesystem still has errors **********

rootfs: 686/8192 files (0.0% non-contiguous), 3994/8192 blocks
```

I will attach a kernel and file system image if you want. Just let me know.

**Comment by fischerling** [comment]
I could reproduce the behavior on current develop 84d5a7ab0592983f27e2b4c4c3a62567681c2c7f.

1. Create a second empty hidden file `files/home/user/.shellrc`
2. Build the filesystem image
3. Start qemu
    1. login as user 
    2. `ls` -> root and README entries are listed
    3. `touch foo`
    4. `ls` -> only foo is listed
    5. `ls -la` -> lists the hidden files and foo

**Comment by fischerling** [comment]
Apparently, when the `.shellrc` file is there to read during the initialization of the shell, this bug happens.

**Comment by Galfurian** [comment]
I'll investigate this bug. Thank you for opening the Issue.
